export const FETCH_FILMS_REQUEST = 'FETCH_FILMS_REQUEST'
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS'
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE'
export const CLEAR_FILM_LIST = 'CLEAR_FILM_LIST'